name: jupyter-actions
channels:
    - conda-forge
dependencies:
  - jupyter=1.0
  - nbformat
  - nbconvert
  - numpy
  - requests=2.24.0
  - pytest
  - sklearn
  - matplotlib
  - seaborn
  - imblearn
  - pandas
  
