on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install -U scikit-learn imblearn pandas seaborn matplotlib numpy jupyterlab pytest
    - name: Run main jupyter
      run: jupyter notebook src/main/jupyter/wniemiec/ml/ppc/main.ipynb
