name: Test-Notebooks

# Run every time a new commit is pushed
on: push

jobs:
  # Set the job key
  Ubuntu:
    # Name the job
    name: Test Jupyter Notebooks
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: jupyter-actions
          environment-file: environment.yml
          python-version: 3.7
      - name: Install dependencies using pip
        run: pip install -U scikit-learn imlearn

      - name: Execute all Notebooks
        shell: bash -l {0}
        run: |
          conda activate jupyter-actions
          pytest

